source("renv/activate.R")
options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))
renv::settings$snapshot.type("explicit")
renv::config$pak.enabled(TRUE)
Sys.setenv(CMDSTAN = here::here(".cmdstan"))