# Created by use_targets().
# Follow the comments below to fill in this target script.
# Then follow the manual to check and run the pipeline:
#   https://books.ropensci.org/targets/walkthrough.html#inspect-the-pipeline

# Load packages required to define the pipeline:
library(here)
library(stantargets)
library(stringi)
library(tidybayes)
library(tarchetypes)
library(targets)
library(qs2)
library(paws.storage)

tar_option_set(
  # Use memory more sparingly
  memory = "transient",
  garbage_collection = TRUE,
  repository = "aws",
  repository_meta = "aws",
  format = "qs",
  controller = crew::crew_controller_local(workers = 1),
  resources = tar_resources(
    tar_resources_aws(
      bucket = Sys.getenv("S3_BUCKET"),
      prefix = "mvn_cases",
      endpoint = Sys.getenv("S3_ENDPOINT"),
      region = Sys.getenv("S3_REGION")
    )
  )
)

# Set target options:
tar_option_set(
  packages = c(
    "bayesplot",
    "cmdstanr",
    "dplyr",
    "ggplot2",
    "posterior",
    "purrr",
    "rlang",
    "stringi",
    "tidybayes",
    "tidyr",
    "qs2"
  )
)

# Run the R scripts in the R/ folder with your custom functions:
tar_source(here("R", "simulation.R"))
tar_source(here("R", "post_processing.R"))
tar_source(here("R", "utils.R"))

# Replace the target list below with your own:
list(
  tar_stan_mcmc(
    name = mcmc,
    stan_files = here("stan", "hirt-hom.stan"),
    data = simulate_data(
      cohort_g = 20,
      judge_gi = 30,
      case_ij = 30,
      types_b = 20
    ),
    chains = 4,
    parallel_chains = 4,
    iter_warmup = 500,
    iter_sampling = 500,
    format = "qs",
    format_df = "qs",
    stdout = R.utils::nullfile(),
    stderr = R.utils::nullfile(),
    return_summary = FALSE
  ),
  # trace plots
  tar_target(
    mcmc_trace_plots,
    bayesplot::mcmc_trace(
      as_draws_array(mcmc_mcmc_hirt.hom),
      pars = paste0("mu_theta[", 1:20, "]")
    )
  ),
  # targets for generating ppc plots
  ## extract y_hat draws generated by Stan
  tar_target(
    mcmc_prediction_draws,
    {
      prediction_draws <- tidybayes::spread_draws(
        mcmc_draws_hirt.hom,
        y_hat[..]
      )[,
        -c(1:3)
      ] |>
        as.matrix()
    }
  ),
  ## output ppc plot
  tar_target(
    mcmc_ppc_plot,
    {
      bayesplot::ppc_bars_grouped(
        y = mcmc_data[["outcome"]],
        yrep = mcmc_prediction_draws,
        group = mcmc_data[[c(".join_data", "g_ij")]]
      ) +
        ggplot2::ggtitle("PPC Check by Cohort")
    }
  ),
  # targets related to validation plot
  tar_target(
    reshaped_posterior,
    reshape_posterior(
      post_array = mcmc_mcmc_hirt.hom |> as_draws_array(),
      param_hat = mu_theta[i],
      order = mcmc_data[[c(".join_data", "g")]]
    )
  ),
  tar_target(
    mcmc_validation_plot,
    {
      # reorder data frame of judge info to match model order
      mcmc_data
      judge_order <- unique(mcmc_data[["ii"]])
      dgp_raw <- mcmc_data[[c(".join_data", "theta_df")]]
      validation_plot(
        data = reshaped_posterior,
        id = id,
        param = mu_theta_hat,
        dgp_df = dgp_raw[judge_order, ]
      )
    }
  )
)
