---
author: Cory Adkins
date: Draft of Febuary 15, 2023
title: Judicial Idealogy and Political Polarization
number-sections: true
geometry:
  - margin=1in
linestretch: 2
indent: true  
mainfont: "Source Serif Pro"
sansfont: "Source Sans Pro"
format: pdf 
bibliography: "../references/references_all.bib"
fontsize: 12pt
---

# Introduction

In 2022, the *Dobbs vs Jackson* ruling ended the federal guarantee of abortion rights in the United States and sparked a debate about the political legitimacy of the Supreme Court. Despite Chief Justice John Roberts' arguments to the contrary, many Americans read the controversial decision as an inappropriate intertwining of legal decision-making and ideological bias. For instance, a Pew Research Center survey conducted after the *Dobbs* decision found that more than 50% of Democrat respondents thought that the Supreme Court did a poor job of keeping their political views out of how they decide cases [@PositiveViewsSupreme2022]. This is nearly double the share of Democratic respondents who reported the same view before the *Dobbs* decision[@PositiveViewsSupreme2022].

One tempting conclusion to draw from *Dobbs* is that the judiciary -- often imagined as politically neutral or, at least, politically insulated -- has finally and fully caught up to the legislative branches in partisan polarization. Indeed, in 21% percent of the Supreme Court's 2021-term decisions, the Justices voted strictly according to the party of their appointing President -- the highest this percentage has been since at least 1953 [@thomson-deveauxJustHowSharp2022]. Public opinion surveys show that the median preference of Supreme Court Justices is much closer to median preferences of the median Republican voter on issues like abortion, health care and civil rights [@jesseeDecadelongLongitudinalSurvey2022].

This paper argues that -- especially outside of the Supreme Court -- polarization among federal judges on "cultural" politics has occurred alongside non-polarization on "economic" politics. On issues like reproductive and LGBTQ rights, the legal profession at large has shifted left. This shift has been countered on the populist right by the appointment of a smaller number of extremist judges to fight in the culture war. On economic politics, judges have shifted right in general, lead by the extreme libertarians of the "Chicago School" and buoyed by a neoliberal interpretation of economic rights shared on both the right and left.

I build this claim on top of a new approach to measuring judicial ideology. Although an enormous body of evidence attests to the presence of ideology among judges, disagreement persists about its content and importance: in particular, whether it may be described one or several dimensions, and how these dispositions impact actual case outcomes.

Drawing on the polarization literature, I argue for a two-dimensional measurement which includes both economic and cultural conservatism. I then briefly review recent efforts to measure judicial ideology, and criticize these measures as too limited to encompass the scope and effects of the federal judiciary, especially when polarization. I then present my own strategy: a multi-dimensional Bayesian ideal point model that I estimate using a new data-set of judicial votes in Federal district and appellate courts.

I conclude by considering the implications of a polarized judiciary in a system of geographically dispersed judicial authority. Unlike polarized Congresspeople, who can produce national legislative "gridlock" by cancelling each other out, federal judges have great scope for unilateral action within narrow geographic bounds. Even a relatively small number of ideologically extreme judges can have an outsize effect as strategic litigants leverage the rules of jurisdiction to self-sort into favorable fora. In this way, the polarized judiciary resembles not federal but state legislative politics - susceptible to capture by well-organized interests within narrow geographical bounds [@grumbachLaboratoriesDemocracyHow2022].

# Measuring Judicial Ideology

In this section, I argue that existing attempts to measure judicial ideology suffer from at least one of three limitations: (1) a failure to incorporate or describe the ideologies of judges in the lower federal and state courts (2); a failure to provide politically meaningful information about judicial ideology; and (3) a failure to incorporate information about case outcomes into the measurement of ideology.

The application of Item-response-theory models to measure legislative ideal points quickly led to adoption in the study of judicial politics. The best known of these early effort is Martin and Quinn's model of Supreme Court justices policy preferences [@martinDynamicIdealPoint2002]. Martin and Quinn use an unidimensional item-reponse-theory model that, crucially, is relatively agnostic about the case content. By using 9 Supreme Court judges (like Scalia and Thomas) as fixed "anchor" points in their model of voting for each term year, Martin and Quinn position justice policy preferences relative to each other justice that term. As Bonica and Sen have argued, this approach ignores selection effects caused by the Court's ability to determine its own docket by granting or denying *certiorari* [@bonicaEstimatingJudicialIdeology2021]. In other words, the political content of the Supreme Court docket varies dramatically from year to year as a result of the Justice's own intervention. Therefore, Martin and Quinn scores cannot be meaningfully compared across term years or with politically meaningful categories.

In contrast to Martin and Quinn's relatively content-agnostic approach, Epstein combines similar IRT models with detailed coding of Supreme Court Cases. [@epsteinJudicialCommonSpace2007] That model therefore permits cross-term comparisons. However, the labor-intensive coding process restricts this method to measuring Supreme Court Justice's ideology only. More recently, Bonica and Sen have avoided the problem of case data entirely by relying on judge's behavior outside the bench. In particular, they use judge's campaign contribution's to place judge's on the same uni dimensional latent space as the politicians that they donate too[@bonicaCommonspaceScalingAmerican2017]. This solves Martin and Quinn's problem of content-agnosticism by matching judges with politically meaningful , but is too tenuously connected to case outcomes. After all, many judges themselves maintain that their personal political preferences do not influence their behavior as judges.

However, all of these models are unidimensional, when we have ample reason to believe that judicial ideology varies across substantive political dimensions. Unfortunately, binary case outcome data is poorly suited to identify models with more than one or two dimensions. [@riversIdentificationMultidimensionalSpatial2003]. Lauderdale and Clark solve the problem of binary data by generating latent categories from a topic model of judicial opinion texts itself [@lauderdaleScalingPoliticallyMeaningful2014]. However, because the categories are generated from case texts, they must take judges at their word about the substantive reasons for their decisions. But, of course, judges often obscure the substantive reasons for their decisions with juridical ones. This model therefore allows cases to hide politics behind legalese, producing substantive categories like "federal, immunity, law" or "congress, act, usc."

My solution is adopt the IRT model first used by Martin & Quinn but to reject its content-agnosticism. Like Epstein I code cases along a left, right dimension so that the results can be interpreted politically meaningfully. However, unlike Epstein, I do not code using textual analysis, but by relying on information about the case's legal category, its parties and its outcome. This allows me to scale the analysis to cover all federal court judges appointed between 1988 and 2020 and to interpret the results political substantively. Finally, it avoids the tenuous connection between case outcomes and judge's behaviors outside the bench. However, consistent with Lauderdale and Clark's critique of low-dimensional models, it relies on an arbitrary assignment of case outcomes to interpretive categories--in my case, cultural and economic conservatism. To overcome this, I justify my choice of dimensions theoretically, but also by using a confirmatory factor analysis (see below).

# Political Polarization and the Judiciary

\[To be added\]

# Data

Until recently, data that links judges and their decisions has been very difficult to obtain, especially for judges outside the Supreme Court. The richest source of data on case outcomes in the federal courts--the Federal Judicial Center's Integrated Database (FJC IDB) --redacts all judge identifying information following the policy set by the Judicial Conference of the United States (JCUS-March 1995). However, the web scraping tools created by the Free Law Project now allow us to link judge names and docket numbers from the public database of court filings (PACER) with the FJC IDB's detailed outcome information [@lissnerWeVeIntegrated2019].

With these records and publicly available biographical information about federal judges, I created a dataset of 23,401 civil cases, filed in the Seventh Circuit between 1988 and 2020. At present, the study is restricted to civil cases under the jurisdiction of the federal courts of the Seventh Circuit. I selected the Seventh Circuit in part because existing evidence shows that assignment of cases among federal judges in that circuit is close to random; this is not the case in every circuit, where jurisdictional rules can produce "judge-shopping" that undermines random assignment [@hubertPoliticalAppointmentsOutcomes2021; @botomanDivisionalJudgeShopping2017]. Furthermore, the seventh circuit is composed of nearly an equal number of Republican and Democratic appointed judges, but also hosts several jurists well known for economic and cultural conservatism---for instance, Judge Richard Posner and (now) Justice Amy Coney Barrett. If polarization appears within any circuit, it should be the Seventh.

Of these cases, 2, 972 are heard by appellate judges sitting in a panel. These panels typically involve 3 judges voting on the same case, resulting in 4 votes (3 from appellate judges and one from a district judge) on the same case item. These appellate cases critically provide a way for us to compare decisions of judges on the same case, and therefore to scale each judge's ideology in reference to the others'.

Finally, these cases are spread across 28 substantive legal categories, ranging from "Antitrust" and "Motor Vehicle Product Liability" to "Civil Rights: Voting" and "Environmental Matters." Cases are assigned to these categories by the district court reporter. To code the case outcomes as right or left leaning, I combine the substantive category with information about whether the outcome favored the plaintiff or defendant with the cases substantive category. For instance, environmental cases with government plaintiff's and business defendants count as "left" outcomes if the plaintiff is victorious. Civil rights: . Some categories provided by the IDB cannot be coded this way unambiguously---for instance, cases involving religious freedom-- . Any involuntary dismissal or final judgement against a party counts as dis favorable, whilst settlements and voluntary dismissals (by far the largest category) are used in the hurdle model (see below), essentially representing a "neutral" outcome.

The full list of coded outcomes is available in the appendix.

# Methods

Two obstacles face any attempt to measure greatest obstacle to measuring judicial ideology *as it arises in actual legal decisions.* The first is that each case is different. While cases fall under broad categories, like civil rights or antitrust, which have clear political consequences, the political meaning of any case in the abstract is always ambiguous. For instance, even the most economically conservative judge sometimes rules against the most egregious monopolies. Without granular data that addresses these case nuances, we are unable to control for important confounders in the relationship between judicial ideology and case outcomes.

Furthermore, which cases even make it to a judge for final decision depend on the litigant's choices about whether to settle their claims - a choice that is itself impacted by the assignment of the judge after the case is filed [@priestSelectionDisputesLitigation1984]. This creates a selection effect whereby only "close" cases receive final judgements. Furthermore, appellate and--especially-- supreme court justices exercise substantial discretion over which cases they decide to rule on, and refuse to hear many more cases than they accept.

My approach to these obstacles relies on overlapping judicial decisions on the same case. Intuitively, we might count a justice who always rules for the plaintiff in civil rights cases as liberal--but may be forced to update our beliefs when we find out the same judge is always upheld by a staunchly conservative panel of appellate judges on those same cases.

In this section, I describe formally how to model this intuition by adapting an item-response-theory model, already widely employed to estimate legislator's ideological preferences. To address the second obstacle, I modify this approach to include a hurdle---.

## 2 Parameter (2PL) Logistic Model

The traditional "2 parameter" IRT model (widely used in legislative ideal-point estimation) relates a respondent *j's* propensity to choose an outcome $y_{ij}$ through an ideal-point $\eta_j$ and an item parameter $\beta_i$ [@clintonStatisticalAnalysisRoll2004]. In the earliest applications of IRT models to educational standardized testing, $\eta_j$ is referred to as the "ability" parameter because it captures the student's ability to correctly answer a question; $\beta_i$ is the "discrimination" parameter because it captures item *i's* ability to distinguish student abilities. The one-dimensional version of this model can be expressed as:

$$
P(y_{ij} | \eta_j, \alpha_i, \beta_i) \sim \Psi^{-1}(\alpha_i+ \beta_i {\eta_j}^\top)
$$

$$
y_{ij} | \eta_j, \alpha_i, \beta_i \sim \text{Bernoulli}(\Psi^{-1}(\alpha_i + \beta_i {\eta_j}^\top))
$$

## Multidimensional 2PL Model with Hurdle

I A simple two-dimensional version of this model captures judicial preference to vote conservative or liberal on a given case *i* just as well as a student's proclivity to answer correctly or incorrectly. However, I make several adaptations to permit model identification in the judicial ideal-point context . First, I fix the ideal points of two judges with well-known policy preferences in either the economic or cultural dimension [@martinDynamicIdealPoint2002; @riversIdentificationMultidimensionalSpatial2003]. In this case, I fix Richard Posner as "1" in the economic dimension and Amy Coney Barrett as "1" in the cultural dimension; all other Seventh Circuit judges are scaled with reference to these ideal points. Second, I add a "hurdle" to my model, following Kubinec [@kubinecIdealstanPackageIdeal2018]. Under the hurdle model, the probability of settling (s = 0) results from the party's propensity to settle (\$\\gamma\$) given the assignment of a judge with ideal point $\eta_j$. This equation formalizes the phenomenon of "strategic" settlement when a disfavorable judge is assigned.

We can express the final model, with two dimensions *d* and a hurdle as:

::: hidden
$$
P(y_{ij} | \eta_j) = \begin{cases}
\text{if } s = 0,\Phi(\gamma_0 + \gamma_1 \eta_j) \\
\text{if } s = 1, (1-\Phi(\gamma_0 +\gamma_1 \eta_j)) \times (\Psi^{-1}(\beta_i \eta_j-\alpha_i))
\end{cases}
$$
:::

-   $\beta_i$ is a $[1 \times d]$ vector of discrimination parameters
-   $\eta_j$ is a $[1 \times d]$ vector of ability parameters
-   $\gamma_1$ is a $[1 \times d]$ vector of settlement parameters
-   $\Psi^{-1}(\mu)$ is the inverse logit function, $\frac{1}{1+\exp(-\mu)}$

Importantly, this model assumes that each judge's ideology is constant across time. Finally, the reduction of votes into latent ideal point estimates does not imply any substantive interpretation of the resulting dimensions. In further work, I plan to test whether "economic" and "cultural" represent plausible interpretations of these dimensions by using a "confirmatory factor analysis" model that constrains [@panChinaIdeologicalSpectrum2018]

# Results and Discussion

*\[To be added\]*

# Works Cited
